config:
  component:
    artifact_id: it-ai-service
    extension: mtar
    group_id: com.sap.it.ai
    mta_id: it-ai-service
    version: ''
  services:
    aicore:
      name: aicore
      service: aicore
      service_plan: sap-internal
