config:
  artifactory:
    host: build-cloud-integration.docker.repositories.sap.ondemand.com
    port: 443
    protocol: https
  nexus:
    host: common.repositories.cloud.sap
    path: /build.snapshots.cpi
    port: 443
    protocol: https
