apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: additional-secrets-app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://github.tools.sap/BIC/bic-product-dev.git
      path: charts/additional-secrets
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
          - $landscape-values/bic/landscape-helm-values/additional-values.yaml
    - repoURL: https://github.tools.sap/BIC/cf-eu12-it-iac-prov.git
      targetRevision: HEAD
      ref: landscape-values
  destination:
    server: SERVER_URL  # Replace SERVER_URL with your Kubernetes cluster server URL
    namespace: ic-controlplane
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
