apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  name: additional-secrets-app
spec:
  destination:
    namespace: ic-controlplane
    server: SERVER_URL
  project: default
  sources:
  - helm:
      valueFiles:
      - values.yaml
      - $landscape-values/bic/landscape-helm-values/additional-values.yaml
    path: charts/additional-secrets
    repoURL: https://github.com/venkatesh-reddy-prog
    targetRevision: HEAD
  - ref: landscape-values
    repoURL: C:\Users\I751676\Desktop\Template_Repo_Folder
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
