apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '7'
  name: btp-secrets
spec:
  destination:
    namespace: ic-controlplane
    server: SERVER_URL
  project: default
  source:
    path: bic/btp-secrets
    repoURL: https://github.com/venkatyuvyfyeckjgikjbkjvkjb
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
