apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: btp-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: https://github.tools.sap/BIC/cf-eu12-it-iac-prov.git
    targetRevision: HEAD
    path: btp-secrets
  destination:
    server: SERVER_URL
    namespace: ic-controlplane
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true