apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '12'
  name: postgres-app
spec:
  destination:
    namespace: ic-controlplane
    server: SERVER_URL
  project: default
  sources:
  - path: bic/landscape-manifests
    repoURL: njdaxbhgxnhx
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    - PruneLast=true
status:
  sync:
    status: Synced
