clm:
  gardenerProject:
    namespace: "garden-bic-dev"
  itSystemID: "it-iac-prov"
  iaasSecretName: "bicdev-aws-secret"
  kafkaVPCIPCIDRBlock: "10.181.0.0/16" #the Kafka cluster's VPC Peering connection CIDR block, default is 10.254.0.0/16, can be different in few cases.
  shoot:
    maxTenantCapInCluster: "40"
    region: "eu-central-1"
    iaasProvider: "aws"
    k8sVersion: "1.30.1"
    emailNotificationReceivers:
      - "nithin.n.k@sap.com"
      - "dhruv.agarwal01@sap.com"
    networks:
      vpcs:
        - id: "vpc-0fd1fc1f0aedfb263"
          cidr: "10.181.0.0/16"
      reservedIPCIDRs: 
        - "10.181.0.0/20"
        - "10.181.16.0/20"
        - "10.181.32.0/20"
        - "10.181.48.0/20"
        - "10.181.80.0/20"
        - "10.181.96.0/20"
        - "10.181.112.0/20"
        - "10.181.128.0/20"
        - "10.181.144.0/20"
        - "10.181.160.0/20"
        - "10.181.176.0/20"
        - "10.181.208.0/20"
        - "10.181.224.0/20"
        - "10.181.240.0/20"
    workers:
      - name: rt-worker
        machineType: m5.xlarge
        gardenLinuxVersion: 1443.9.0

postgres:
  parentInstanceName: "lm-pg-instance-eu12"