clm:
  gardenerProject:
    namespace: "garden-bic-dev"
  itSystemID: "it-iac-prov"
  iaasSecretName: "bicdev-aws-secret"
  kafkaVPCIPCIDRBlock: "10.254.0.0/16" #the Kafka cluster's VPC Peering connection CIDR block, default is 10.254.0.0/16, can be different in few cases.
  shoot:
    maxTenantCapInCluster: "40"
    region: "eu-central-1"
    iaasProvider: "aws"
    k8sVersion: "1.30.1"
    emailNotificationReceivers:
      - "nithin.n.k@sap.com"
      - "dhruv.agarwal01@sap.com"
    networks:
      vpcs:
        - id: "vpc-01550fe85b024c747"
          cidr: "10.182.0.0/16"
    workers:
      - name: rt-worker
        machineType: m5.xlarge
        gardenLinuxVersion: 1443.9.0

postgres:
  parentInstanceName: "lm-pg-instance-eu12"
  
vault:
  certs:
    secretName: "vhcertificates"
  secretStoreRef:
    name: "vault-backend"

image:
  pullPolicy: "Always"
  imageNamespace: "com.sap.it.img.dev"
  imageName: "ic-lifecycle-manager"
  tag: "iac.latest"
