clm:
  gardenerProject:
    namespace: garden-bic-dev
  iaasSecretName: bicdev-aws-secret
  itSystemID: it-iac-prov
  kafkaVPCIPCIDRBlock: 10.254.0.0/16
  shoot:
    emailNotificationReceivers:
    - nithin.n.k@sap.com
    - dhruv.agarwal01@sap.com
    iaasProvider: aws
    k8sVersion: 1.30.1
    maxTenantCapInCluster: '40'
    networks:
      vpcs:
      - cidr: 10.182.0.0/16
        id: vpc-01550fe85b024c747
    region: eu-central-1
    workers:
    - gardenLinuxVersion: 1443.9.0
      machineType: m5.xlarge
      name: rt-worker
image:
  imageName: ic-lifecycle-manager
  imageNamespace: com.sap.it.img.dev
  pullPolicy: Always
  tag: iac.latest
postgres:
  parentInstanceName: lm-pg-instance-eu12
vault:
  certs:
    secretName: vhcertificates
  secretStoreRef:
    name: vault-backend
