config:
  component:
    artifact_id: web-assembly
    extension: mtar
    group_id: com.sap.it.rc
    mta_id: it-rc-web
    version: ''
  services:
    postgresql_rc:
      engine_version: '12'
      memory: '2'
      multi_az: false
      name: it-db-rc
      server_type: ''
      service: postgresql-db
      service_plan: standard
      storage: '200'
