apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications/btp-secrets.yaml
  - applications/additional-secrets.yaml
  - applications/postgres-app.yaml
  - bic-product-dev/applications/istio-base-app.yaml
  - bic-product-dev/applications/istio-istiod-app.yaml
  - bic-product-dev/applications/istio-gateway-app.yaml
  - bic-product-dev/applications/bom-secrets.yaml
  - bic-product-dev/applications/cert-manager.yaml
  # - bic-product-dev/applications/fluentbit-app.yaml
  # - bic-product-dev/applications/dynatrace-operator-app.yaml
  # - bic-product-dev/applications/dynatrace-app.yaml
  - bic-product-dev/applications/btp-operator-app.yaml
  - bic-product-dev/applications/ic-lifecycle-manager.yaml
  - bic-product-dev/applications/external-secrets-app.yaml
  - bic-product-dev/applications/vh-deployer.yaml
patches:
  - path: patches/gateway-values.yaml
    target:
      kind: Application
      name: istio-gateway-app
  - path: patches/ic-lifecycle-manager-overlay.yaml
    target:
      kind: Application
      name: ic-lifecycle-manager  
  - path: patches/ic-virtual-host-manager-overlay.yaml
    target:
      kind: Application
      name: ic-virtual-host-manager
  - path: patches/common-patch.yaml
    target:
      kind: Application         
  # - path: patches/dynatrace-overlay.yaml
  #   target:
  #     kind: Application 
  #     name: dynatrace-operator-app 