apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-eu12-it-iac-prov-root-app
spec:
  destination:
    namespace: sf-2e4ac807-c35b-4604-a175-53c4a37c0177
    server: wertty
  project: default
  source:
    kustomize:
      namePrefix: iac-prov-
    path: bic
    repoURL: iwkjvbkjb
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - Replace=true
