apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: cf-eu12-it-iac-prov/kv/data/btpoperator
  name: sap-btp-service-operator
  namespace: ic-controlplane
stringData:
  clientid: <venkatesh/kv/data/btpoperator#clientid>
  sm_url: <Modify/kv/data/btpoperator#sm_url>
  tls.crt: <avp:path:cf-eu12-it-iac-prov/kv/data/btpoperator#certificate>
  tls.key: <avp:path:cf-eu12-it-iac-prov/kv/data/btpoperator#key>
  tokenurl: <avp:path:cf-eu12-it-iac-prov/kv/data/btpoperator#certurl>
  tokenurlsuffix: /oauth/token
type: opaque
