apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-secrets
  namespace: dynatrace
  annotations:
    avp.kubernetes.io/path: "cf-eu12-it-iac-prov/kv/data/dynatrace"
type: Opaque
data:
  apiToken: <avp:path:cf-eu12-it-iac-prov/kv/data/dynatrace#apiToken>
  dataIngestToken: <avp:path:cf-eu12-it-iac-prov/kv/data/dynatrace#dataIngestToken>
