apiVersion: v1
kind: Namespace
metadata:
  name: fluentbit

---

apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-secret
  namespace: fluentbit # Change namespace, if needed
  labels:
    app: fluent-bit
  annotations:
    avp.kubernetes.io/path: "kv/data/fluentbit"  
stringData:
  # Configure `Host`, `HTTP_User`, `HTTP_Passwd`
  output-http.conf: |
    [OUTPUT]
        Name  http
        Match *
        Host ingest-sf-9a10e54d-d8fd-4c66-9132-ea7ff968d6c6.cls-03.cloud.logs.services.sap.hana.ondemand.com
        Port 443
        HTTP_User <avp:path:kv/data/fluentbit#userName>
        HTTP_Passwd <avp:path:kv/data/fluentbit#password>
        tls true
        Compress gzip
        URI /
        Format json
---