apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "ic-lifecycle-manager"
  name: lm-gardener-project-kubeconfig
  annotations:
    avp.kubernetes.io/path: "cf-eu12-it-iac-prov/kv/data/lifecyclemanager"
type: Opaque
stringData:
  kubeconfig.yaml: <avp:path:cf-eu12-it-iac-prov/kv/data/lifecyclemanager#gardenerKubeConfig>