apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: cf-eu12-it-iac-prov/kv/data/lifecyclemanager
  labels:
    app: ic-lifecycle-manager
  name: lm-gardener-project-kubeconfig
stringData:
  kubeconfig.yaml: <avp:path:cf-eu12-it-iac-prov/kv/data/lifecyclemanager#gardenerKubeConfig>
type: Opaque
