apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: kv/data/btpoperator2
  name: fluentbit-secret
  namespace: default
stringData:
  password: <avp:path:kv/data/btpoperator2#password>
  sm_url: <avp:path:kv/data/btpoperator2#sm_url>
  tokenurl: <avp:path:kv/data/btpoperator2#tokenurl>
type: opaque
