apiVersion: v1
kind: Secret
metadata:
  name: fluentbit-secret
  namespace: default
  annotations:
    avp.kubernetes.io/path: "kv/data/btpoperator2"
type: opaque
stringData:
  sm_url: <avp:path:kv/data/btpoperator2#sm_url>
  password: <avp:path:kv/data/btpoperator2#password>
  tokenurl: <avp:path:kv/data/btpoperator2#tokenurl>
