apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ignored
spec:
  destination:
    server: 'https://api.eu12-iac-prov.bic-dev.shoot.canary.k8s-hana.ondemand.com'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - Replace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled 