apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ignored
spec:
  destination:
    server: Modify
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
    - Replace=true
