kind: Application
metadata:
  name: istio-gateway-app
spec:
  sources:
  - chart: gateway
    helm:
      valueFiles:
      - $prod-values/charts/istio/gateway-values.yaml
      - $landscape-values/bic/landscape-helm-values/gateway-values.yaml
    repoURL: https://common.repositories.cloud.sap/artifactory/istio-release-remote/charts/
    targetRevision: 1.22.1
  - ref: prod-values
    repoURL: https://github.tools.sap/BIC/bic-product-dev.git
    targetRevision: HEAD
  - ref: landscape-values
    repoURL: Modify
    targetRevision: HEAD
